/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Erik' at '11.09.17 14:27' with Gradle 2.13
 *
 * @author Erik, @date 11.09.17 14:27
 */
public class Weather {
    public boolean someLibraryMethod() {
        return true;
    }
}
