import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Erik' at '11.09.17 14:27' with Gradle 2.13
 *
 * @author Erik, @date 11.09.17 14:27
 */
public class WeatherTests {
    @Test public void getTodaysWeather() {
        
        	fail();
        }  
    
    @Test public void get3DaysForecartWeather() {
        
    	fail();
    } 
    
    @Test public void getCityCoordinates() {
        
    	fail();
    } 
    
    }

